### ISSUE TITLE
Using base64 instead of plain SVG in data-uri's

### ISSUE THREAD

**Issue by davidhund** [buseca/patternbolt#1]
I believe encoding the svg to base64 and using those in the data-uri has better browser support (IE9?). Also: if you are using plain svg you should url-encode certain chars such as # -› %23. Check out http://css-tricks.com/using-svg/ and http://r.va.gg/2012/05/data-uri-svg.html

**Comment by buseca** [comment]
thank you so much for the links, I 'll do a serious research about the encoding solutions, but at the moment I'm a little bit doubtful because this would make the svg code less clear and less editable. Es: with the current solution you can easily change the fill color changing the "fill" property in the svg code. If I'd go for base64, the property will be no more accessible.

**Comment by buseca** [comment]
I finally decided to go for the escape (%) solution as it ensure IE9+ compatibility, as you suggested.
But no hope for IE8, as predictable. Tnx David
